# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - develop
      - test
      - main

pool:
  vmImage: ubuntu-latest

steps:

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud Konex Innovation'
      organization: 'konexinnovation-sonacloud'
      scannerMode: 'Other'
      extraProperties: |
        # Additional properties that will be passed to the scanner, 
        # Put one key=value per line, example:
        # sonar.exclusions=**/*.bin
        sonar.projectKey=KonexInnovation_pagatodo-backend-financiera-contable
        sonar.projectName=pagatodo-backend-financiera-contable

  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'KonexInnovation'

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'
      publishJUnitResults: true
      testResultsFiles: '$(Build.Repository.LocalPath)/**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: true
      sqMavenPluginVersionChoice: 'latest'
      checkStyleRunAnalysis: true

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: '$(Build.Repository.LocalPath)/**/site/jacoco/jacoco.xml'
      reportDirectory: '$(Build.Repository.LocalPath)/**/site/jacoco'

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'verify -DskipTests=true'

  - task: CopyFiles@2
    inputs:
      Contents: '**'
      TargetFolder: '$(build.artifactstagingdirectory)'
      
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'pagatodo-backend-financiera-contable-artifact'
      publishLocation: 'Container'