# Configuracion del springboot server
server:
  port: 8255
  servlet:
    context-path: /api/v1/financiera-contable

# Configuracion springdoc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    #use-root-path: true
  api-docs:
    path: /swagger.v1+json
  api:
    title: Financiera Contable API
    description: Financiera Contable API's proporciona servicios para todo el control de las operaciones financieras y contables
    version: 1.0
spring:
  config:
    activate:
      on-profile: prod
    application:
      name: pagatodo-backend-financiera-contable
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate.default_schema: ${db.schema}
      jdbc:
        lob:
          non_contextual_creation: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.OracleDialect
  feign:
    client:
      config:
        default:
          connectTimeout: 2000
          readTimeout: 2000
          loggerLevel: basic

# reglas de seguridad
security:
  #oauth2:
  #  issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/ms_parametrizaciones
  privileges:
    enable: true
    permit-all:
      - /swagger-ui/**
      - /swagger.v1+json/**
    rules:
      rule1:
        name: roles
        matchers:
          - /roles/**

request-mapping:
  controller:
    gestion-caja: gestion-caja
    apertura-caja: apertura-caja
    ingreso: ingreso
    parametrizacion-concepto: parametrizacion-concepto
    gestion-egreso-caja: gestion-egreso-caja
    programar-pago: programar-pago
    anulacion: anulacion
    traslado: traslado
    libro-diario: libro-diario
    cerrar-caja: cerrar-caja
    cartera: cartera
    conciliacion: conciliacion
    recaudo-cartera: recaudo-cartera

url:
  administrar-vendedores-client: ${url.administrar-vendedores-client}
  estructura-comercial-client: ${url.estructura-comercial-client}

log4j:
  configurationFile: log4j2-spring.xml,log4j2-env.xml